# 数据库配置
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8'
    username: root
    password: 123456

# mybatis-plus配置
mybatis-plus:
  # mapper文件位置
  mapper-locations:
    - classpath:**/*.xml